# Generated by Django 2.1.11 on 2020-03-24 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cupboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRecipeJunction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cupboard.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=100, unique=True)),
                ('ingredients', models.ManyToManyField(through='recipe.ItemRecipeJunction', to='cupboard.Item')),
            ],
        ),
        migrations.AddField(
            model_name='itemrecipejunction',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.Recipe'),
        ),
    ]
