# Generated by Django 3.0.5 on 2020-05-10 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('item_category', models.CharField(choices=[('MEAT', 'Meat'), ('VEGETABLE', 'Vegetable'), ('FRUIT', 'Fruit'), ('DAIRY', 'Dairy'), ('GRAIN', 'Grain'), ('FROZEN', 'Frozen'), ('OTHER', 'Other')], default='OTHER', max_length=9)),
                ('price_per_cup', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
            ],
        ),
    ]
