# Generated by Django 3.1.2 on 2020-10-05 21:08

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, unique=True)),
                ('price_per_cup', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price_per_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
        ),
    ]
