# Generated by Django 2.1.11 on 2021-09-16 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cupboard', '0002_auto_20210809_1322'),
        ('cupboard', '0002_auto_20210827_2031'),
    ]

    operations = [
    ]
